### ISSUE TITLE
No suitable driver found for true (SQL Server JDBC driver)

### ISSUE THREAD

**Issue by itssrihere** [quarkiverse/quarkus-mcp-servers#20]
spring:
    application:
        name: spring-ai-demo
    ai:
        mcp:
            client:
                stdio:
                    connections:
                        jdbc:
                            command: java
                            args:
                                - -jar
                                - mcp-server-jdbc.jar
                                - --jdbc.url=jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true
                                - --jdbc.user=sa
                                - --jdbc.password=P@ssw0rd1

Error message "io.quarkiverse.mcp.server.ToolCallException: Failed to list tables: for jdbcUrl=true"

Added dependency

<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>11.2.3.jre17</version>
        </dependency>

And built the project locally, and copied the mcp server jdbc jar to my demo project. Looks like the = part of the jdbc url is not being parsed correctly?

**Comment by maxandersen** [comment]
what is the first many lines about:

```
spring:
application:
name: spring-ai-demo
ai:
mcp:
client:
stdio:
connections:
jdbc:
```

?

**Comment by itssrihere** [comment]
Kindly ignore them. I was just pasting the app props. The pertinent details are the command and the args. Specifically the jdbc url. Seems like the moment I have to pass extra params, viz. encrypt=false;trustServerCertificate=true causes issues.

**Comment by maxandersen** [comment]
try '--jdbc.url="jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true"' ? not sure how springai's config parses/handles the quoting

**Comment by maxandersen** [comment]
@itssrihere did that work for you?

**Comment by itssrihere** [comment]
@maxandersen - I apologize for the late response. I was able to workaround this by adding the props as environment variables (like below)

```
                stdio:
                    connections:
                        jdbc:
                            command: java
                            args:
                                - -jar
                                - mcp-server-jdbc.jar
                            env:
                                JDBC_URL: jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true
                                JDBC_USER: user
                                JDBC_PASSWORD: pass
```
